### ISSUE TITLE
Fehler beim Lesen der Werte

### ISSUE THREAD

**Issue by SmartyML** [iobroker-community-adapters/ioBroker.oilfox#68]
Nachfolgender Fehler lässt sich nicht lösen:

<html>
<body>

host.iobroker-test |   | 2021-11-27 13:13:01.565 | error | instance system.adapter.oilfox.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | -- | --
oilfox.0 | 1315 | 2021-11-27 13:13:01.055 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
oilfox.0 | 1315 | 2021-11-27 13:13:01.055 | info | terminating
oilfox.0 | 1315 | 2021-11-27 13:13:00.552 | error | Unexpected token < in JSON at position 0
oilfox.0 | 1315 | 2021-11-27 13:13:00.552 | error | SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:75:31) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)
oilfox.0 | 1315 | 2021-11-27 13:13:00.552 | error | uncaught exception: Unexpected token < in JSON at position 0

</body>
</html>

**Comment by SmartyML** [comment]
Version 3.1.0 funktioniert. Installieren mit

./iobroker url "https://github.com/iobroker-community-adapters/ioBroker.oilfox/tarball/master" oilfox --debug

Anschließend unter Adapter Upload und eine Instanz hinzufügen.
