### ISSUE TITLE
settings cannot be opened

### ISSUE THREAD

**Issue by Goeste** [iobroker-community-adapters/ioBroker.oilfox#82]
I cannot open the settings anymore since updating to 4.1.1.

The console throws the following error:
`instrument.ts:124 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.value (ConfigPanel.js:124:23)
    at a.value (ConfigPanel.js:262:31)
    at Go (react-dom.production.min.js:187:188)
    at Uo (react-dom.production.min.js:186:173)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at n.m.setState (react.production.min.js:12:369)
    at index.js:148:34`

I updated since I got the following error and did not get any updates:
`host.ioBroker
2022-04-07 09:29:04.385	error	instance system.adapter.oilfox.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

oilfox.0
2022-04-07 09:29:03.313	error	Unexpected token < in JSON at position 0

oilfox.0
2022-04-07 09:29:03.312	error	SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:65:27) at IncomingMessage.emit (node:events:402:35) at endReadableNT (node:internal/streams/readable:1343:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)

oilfox.0
2022-04-07 09:29:03.310	error	uncaught exception: Unexpected token < in JSON at position 0
`

Best, goeste

**Comment by Weihrich** [comment]
I have the same issue, after deinstalling 4.0.3 and doing a fresh install with 4.1.1 the settings page in iobroker is not accessible.

**Comment by HighControl** [comment]
Gleicher Fehler, leider

**Comment by xelarep** [comment]
Unfortunately same here :-(

No settings page, even after removing and new installation to 4.1.1 due to api changes…

how can I support, what do you need?

**Comment by xelarep** [comment]
Gone with v4.1.2! Thx!

**Comment by Goeste** [comment]
kann ich bestätigen. Gone mit 4.1.2!

vielen Dank!
